# Generated by Django 4.2.3 on 2023-08-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diploma",
            fields=[
                (
                    "uuid",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("sha512sum", models.CharField(max_length=100)),
            ],
        ),
    ]
